del /f /q check-db.js
del /f /q check-payments-structure.js
del /f /q check-tables.js
del /f /q remove-history-table.js
del /f /q migrations\cleanup_payments_table.js
del /f /q migrations\fix_payments_table.js
del /f /q migrations\force_remove_payment_history.js
del /f /q migrations\rebuild_payments_table.js
del /f /q migrations\remove_payment_history.js
del /f /q migrations\restructure_payments.js
